const SneakRules = [
	{ field: 'name', rules: 'isName'},
	{
		field: 'mobile',
		or: [
			{ field: 'contact', rules: 'isWx'}
		],
		rules: 'isPhone'
	},
	{ field: 'building' },
	{ field: 'start_time' },
	{ field: 'sales_channel_type'},
	{ field: 'sales_channel'},
	{ field: 'star' },
]

const addBillRules = [
	{ field: 'name', rules: 'isName'},
	{ field: 'phone', rules: 'isPhone'},
	{ field: 'age', rules: 'isAge'},
	{ field: 'product_bank_id' },
	{ field: 'product_id' },
	{ field: 'apply_money', rules: 'isMoney' },
	{ field: 'building_name' },
	{ field: 'house_area', rules: 'isMoney' },
	{ field: 'is_secondhand' },
	{ field: 'relation' },
	{ field: 'handover_type' },
	{ field: 'buying_option' },
	{ field: 'decoration_schedule' },
	{ field: 'decoration_company_name' },
	{ field: 'decoration_type' },
	{ field: 'sales_channel_type'},
	{ field: 'sales_channel'},
	{ field: 'service_time'},
	{ field: 'service_place'},
	{ field: 'perpare_material'},
	{ field: 'need_gift'}
]

const validateCodeRules = [
	{ field: 'account', rules: 'isPhone'},
	{ field: 'v_code', rules: 'isCode'}
]

const faceSignRules = [
	{ field: 'apply_id'},
	{ field: 'product_id'},
	{ field: 'contract_number', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'name', rules: 'isName'},
	{ field: 'idcard_number', rules: 'isIdcard', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'phone', rules: 'isPhone' },
	{ field: 'relation', need: [ {field: 'commission_type', value: 1} ]},
	{ field: 'apply_money', rules: 'isMoney' },
	{ field: 'apply_periods' },
	{ field: 'commission_type' },
	{ field: 'building_name' },
	{ field: 'building_id' },
	{ field: 'house_area', rules: 'isMoney' },
	{ field: 'room_number' },
	{ field: 'house_type' },
	{ field: 'house_category'},
	{ field: 'is_secondhand'},
	{ field: 'decoration_type', need: [ {field: 'commission_type', value: 1} ]},
	{ field: 'decoration_schedule', need: [ {field: 'commission_type', value: 1} ]},
	{ field: 'buying_option', need: [ {field: 'commission_type', value: 1} ]},
	{ field: 'handover_type'},
	{ field: 'job_type', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'idcard_pics', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'property_pics', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'credit_apply_pics', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'scene_pics', need: [ {field: 'commission_type', value: 1} ]},
	{ field: 'notification_service_contract_pics', need: [ {field: 'commission_type', value: 1} ]},
	{ field: 'bank_signer', rules: 'isName'},
	{ field: 'material_complete' },
	{ field: 'material_complete_reason', need: [ {field: 'material_complete', value: 1} ] },
	{ field: 'lack_document_type', need: [ {field: 'material_complete', value: 1} ] },
	{ field: 'sign_type' },
	{ field: 'survey_comment' },
	{ field: 'decoration_company_name', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'decoration_company', need: [ {field: 'commission_type', value: 1} ] },
	{ field: 'sign_bank'},
	{ field: 'sign_bank_name'},
	{ field: 'sign_place'},
	{ field: 'location_gps'}
]

const fastFaceSignRules = [
	{ field: 'isNeedHelp'},
	{ field: 'colleague_id', need: [ {field: 'isNeedHelp', value: 1} ]},
	{ field: 'colleague_name', need: [ {field: 'isNeedHelp', value: 1} ]},
	{ field: 'bank_id'},
	{ field: 'product_id'},
	{ field: 'contract_number' },
	{ field: 'name', rules: 'isName'},
	{ field: 'idcard_number', rules: 'isIdcard' },
	{ field: 'phone', rules: 'isPhone' },
	{ field: 'relation'},
	{ field: 'apply_money', rules: 'isMoney' },
	{ field: 'apply_periods' },
	// { field: 'commission_type' },
	{ field: 'building_name' },
	{ field: 'building' },
	{ field: 'house_area', rules: 'isMoney' },
	{ field: 'room_number' },
	{ field: 'house_type' },
	{ field: 'house_category'},
	{ field: 'is_secondhand'},
	{ field: 'decoration_type'},
	{ field: 'decoration_schedule'},
	{ field: 'buying_option'},
	{ field: 'handover_type'},
	{ field: 'job_type' },
	{ field: 'mortgage_bank' },
	{ field: 'idcard_pics' },
	{ field: 'property_pics' },
	{ field: 'credit_apply_pics' },
	{ field: 'scene_pics'},
	{ field: 'notification_service_contract_pics'},
	{ field: 'bank_staff', rules: 'isName'},
	{ field: 'bank_signer', rules: 'isName'},
	{ field: 'material_complete' },
	{ field: 'material_complete_reason', need: [ {field: 'material_complete', value: 1} ] },
	{ field: 'lack_document_type', need: [ {field: 'material_complete', value: 1} ] },
	{ field: 'sign_type' },
	{ field: 'survey_comment' },
	{ field: 'decoration_company_name' },
	{ field: 'decoration_company' },
	{ field: 'sign_bank'},
	{ field: 'sign_bank_name'},
	{ field: 'sign_place'},
	{ field: 'location_gps'}
]

export {
	SneakRules,
	addBillRules,
	validateCodeRules,
	faceSignRules,
	fastFaceSignRules
}